export default function Head() {
  return (
    <>
      <title>Google Clone Next js 13</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta content="Generated by create next app" name="description" />
      <link href="../../public/favicon.svg" rel="icon" />
    </>
  );
}
